### ISSUE TITLE
Add license check

### ISSUE THREAD

**Issue by boyum** [Tietoevry-Create/h5p-bildetema#606]
Each 3rd party package should be open source and we should use [`license-checker`](https://npmjs.com/license-checker) to check them. It should be a PR check.

Use `--onlyAllow 'MIT;ISC;Apache-2.0;Apache 2.0;BSD;WTFPL;Artistic-2.0;CC0-1.0;CC-BY-3.0;Unlicense;Public Domain;` as license filter.

- [ ] Install `license-checker`
- [ ] Add GitHub workflow

**Comment by ekrof** [comment]
Please assign me please pretty
